/**
 * Parity guard: pkgist's PUBLISHED subpath keys vs. the SOURCE `exports` map.
 *
 * ## Why this exists
 *
 * `web@a39596c` documented `import { invalidatePageCache } from
 * "@warlock.js/web/server"` and it worked in the monorepo (source
 * `web/package.json` mapped `"./server"` straight at
 * `src/server/page-cache.ts`) but FAILED for every real consumer: the
 * published package.json is generated by pkgist from `pkgist.config.ts`'s
 * `entries` list, keyed by file path — and `entries` already had a SEPARATE
 * `server/index.ts` entry (the internal pipeline seam) that pkgist derives
 * as `"./server"` too. Source and published export maps silently disagreed;
 * nothing caught it because nothing compared them.
 *
 * ## The derivation rule (read from pkgist itself, not guessed)
 *
 * `builder/node_modules/@mongez/pkgist/esm/files/package-json.mjs`'s
 * `entryPaths()` (lines 91-104) turns an `entries` path into its exports
 * key:
 *   - `index.ts`        -> "."             (basename "index" at the root)
 *   - `x/index.ts`       -> "./x"           (basename "index" -> parent dir)
 *   - `x.ts`             -> "./x"           (any other basename -> itself)
 *
 * This file reimplements exactly that rule (`entryToExportPath` below) so
 * the two can be compared without executing a real pkgist build.
 *
 * ## What this checks
 *
 * For every package in `pkgist.config.ts` that has BOTH an `entries` list
 * AND a source `package.json` with an `exports` map, the set of keys pkgist
 * will publish must equal the source `exports` keys — minus an explicit,
 * reasoned ALLOWLIST for keys that are provably intentional internal seams
 * (an entry that exists so the seam's module graph survives tree-shaking,
 * but is deliberately not a public `exports` key).
 *
 * A package with `entries` but no source `exports` map (e.g.
 * `@warlock.js/core`, which ships no `exports` field at all) is not
 * comparable and is skipped, not silently passed — see `isComparable`.
 */
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import pkgistConfig from "../pkgist.config.ts";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/** builder/scripts -> builder. */
export const BUILDER_ROOT = path.resolve(__dirname, "..");

export interface AllowlistEntry {
  /** The package name exactly as it appears in `pkgist.config.ts`. */
  packageName: string;
  /** The published exports key pkgist derives, e.g. "./server". */
  exportPath: string;
  reason: string;
}

/**
 * Keys pkgist WILL publish that are deliberately absent from the source
 * `exports` map — an internal seam kept alive only so its module graph is
 * not tree-shaken, never meant to be a public import path. Each entry is
 * scoped to one package + one exact key, so a future genuine drift on a
 * different key still fails loudly.
 */
export const ALLOWLIST: ReadonlyArray<AllowlistEntry> = [
  {
    packageName: "@warlock.js/web",
    exportPath: "./entry",
    reason:
      "the hydration entry (`entry/index.ts`) is a Vite BUILD INPUT, not a package specifier any consumer imports — `warlock build` feeds it to Vite by path, never by `@warlock.js/web/entry`. Kept as an entry only so its export surface survives tree-shaking; deliberately absent from source `exports` (pkgist.config.ts:407-422).",
  },
  {
    packageName: "@warlock.js/web",
    exportPath: "./server",
    reason:
      "the pipeline seam (`server/index.ts`) is reached only by the dev connector's `ssrLoadModule` on a runtime path string, never by a package specifier -- that file's own header forbids making its surface (executePageRequest, installPageRoutes, ...) publicly importable. The PUBLIC server-only subpath is \"./page-cache\" (`page-cache.ts`, a separate entry) -- see pkgist.config.ts:439-452.",
  },
];

/** basePath / exportPath pair pkgist derives for one `entries` string. */
export interface DerivedEntry {
  entry: string;
  exportPath: string;
}

/**
 * Mirrors `@mongez/pkgist`'s `entryPaths()` exactly
 * (`node_modules/@mongez/pkgist/esm/files/package-json.mjs:91-104`):
 * strip a `.ts`/`.tsx` extension, then if the basename is "index" the
 * export path is the parent directory (or "." at the root); otherwise the
 * export path is the entry's own (extensionless) path.
 */
export function entryToExportPath(entry: string): string {
  const basePath = entry.replace(/\.tsx?$/, "");
  const parts = basePath.split("/");
  const last = parts[parts.length - 1];

  if (last === "index") {
    const dir = parts.slice(0, -1).join("/");
    return dir ? `./${dir}` : ".";
  }

  return `./${basePath}`;
}

export interface ConfiguredPackage {
  name: string;
  root: string;
  entries?: readonly string[];
}

/** Flattens `standalone` + every `families[].packages` into one list. */
export function collectConfiguredPackages(config: typeof pkgistConfig): ConfiguredPackage[] {
  const packages: ConfiguredPackage[] = [];

  for (const pkg of config.standalone ?? []) {
    packages.push(pkg as ConfiguredPackage);
  }

  for (const family of config.families ?? []) {
    for (const pkg of family.packages) {
      packages.push(pkg as ConfiguredPackage);
    }
  }

  return packages;
}

/** A package is only comparable when it declares BOTH `entries` and a source `exports` map. */
export function isComparable(
  pkg: ConfiguredPackage,
  sourceExportsKeys: string[] | undefined,
): boolean {
  return Boolean(pkg.entries && pkg.entries.length > 0 && sourceExportsKeys);
}

export function readSourceExportsKeys(
  builderRoot: string,
  configuredRoot: string,
): string[] | undefined {
  const pkgJsonPath = path.resolve(builderRoot, configuredRoot, "package.json");
  let raw: string;
  try {
    raw = readFileSync(pkgJsonPath, "utf8");
  } catch {
    return undefined;
  }

  const json = JSON.parse(raw) as { exports?: Record<string, unknown> };
  if (!json.exports) return undefined;

  return Object.keys(json.exports);
}

export interface ParityViolation {
  packageName: string;
  /** Keys pkgist will publish that the source `exports` map does not have, and that are not allowlisted. */
  publishedOnly: string[];
  /** Keys the source `exports` map has that pkgist will NOT publish. */
  sourceOnly: string[];
}

export interface ParityReport {
  comparedPackages: string[];
  skippedPackages: string[];
  violations: ParityViolation[];
}

/**
 * Pure comparison, standalone from `pkgist.config.ts`/filesystem access so
 * tests can exercise it directly on fixtures.
 */
export function compareOnePackage(
  pkg: ConfiguredPackage,
  sourceExportsKeys: string[],
): ParityViolation | undefined {
  const publishedKeys = new Set((pkg.entries ?? []).map(entryToExportPath));
  const sourceKeys = new Set(sourceExportsKeys);
  const allowlisted = new Set(
    ALLOWLIST.filter((entry) => entry.packageName === pkg.name).map((entry) => entry.exportPath),
  );

  const publishedOnly = [...publishedKeys]
    .filter((key) => !sourceKeys.has(key) && !allowlisted.has(key))
    .sort();
  const sourceOnly = [...sourceKeys].filter((key) => !publishedKeys.has(key)).sort();

  if (publishedOnly.length === 0 && sourceOnly.length === 0) return undefined;

  return { packageName: pkg.name, publishedOnly, sourceOnly };
}

export function runPkgistExportsParityGate(
  builderRoot: string,
  config: typeof pkgistConfig,
): ParityReport {
  const comparedPackages: string[] = [];
  const skippedPackages: string[] = [];
  const violations: ParityViolation[] = [];

  for (const pkg of collectConfiguredPackages(config)) {
    const sourceExportsKeys = readSourceExportsKeys(builderRoot, pkg.root);
    if (!isComparable(pkg, sourceExportsKeys)) {
      skippedPackages.push(pkg.name);
      continue;
    }

    comparedPackages.push(pkg.name);
    const violation = compareOnePackage(pkg, sourceExportsKeys as string[]);
    if (violation) violations.push(violation);
  }

  return { comparedPackages, skippedPackages, violations };
}

function formatReport(report: ParityReport): { text: string; failed: boolean } {
  const lines: string[] = [];
  lines.push(
    `pkgist-exports-parity: compared ${report.comparedPackages.length} package(s) with both entries + source exports (${report.comparedPackages.join(", ") || "none"}); skipped ${report.skippedPackages.length} not comparable.`,
  );
  lines.push("");

  if (report.violations.length === 0) {
    lines.push(
      "Clean -- pkgist's published subpath keys match each comparable package's source exports map.",
    );
    return { text: lines.join("\n"), failed: false };
  }

  lines.push(`FAILED -- ${report.violations.length} package(s) with mismatched exports keys:`);
  lines.push("");
  for (const v of report.violations) {
    if (v.publishedOnly.length > 0) {
      lines.push(
        `  ${v.packageName}: pkgist will publish ${JSON.stringify(v.publishedOnly)} which the source exports map does not have (and which is not on the ALLOWLIST).`,
      );
    }
    if (v.sourceOnly.length > 0) {
      lines.push(
        `  ${v.packageName}: source exports map has ${JSON.stringify(v.sourceOnly)} which pkgist's entries list will NOT publish.`,
      );
    }
  }
  lines.push("");
  lines.push(
    "Either add/remove the matching pkgist.config.ts `entries` line, add/remove the matching source " +
      "package.json `exports` key, or -- only for a provably intentional internal seam -- add a scoped " +
      "{ packageName, exportPath, reason } entry to ALLOWLIST in this file.",
  );

  return { text: lines.join("\n"), failed: true };
}

async function main(): Promise<number> {
  const report = runPkgistExportsParityGate(BUILDER_ROOT, pkgistConfig);
  const { text, failed } = formatReport(report);
  console.log(text);
  return failed ? 1 : 0;
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === __filename;
if (isMain) {
  main().then((code) => process.exit(code));
}
